#PBS -l walltime=1240:00:00
#PBS -l nodes=1:ppn=1
#PBS -q qgroup
#PBS -j oe

cd $PBS_O_WORKDIR

export PATH=/opt/gridview/pbs/dispatcher-sched/sbin/:/opt/gridview/pbs/dispatcher/sbin/:/opt/gridview/pbs/dispatcher-sched/bin/:/opt/gridview/pbs/dispatcher/bin/:/checkpoints/home/zzw2/bin:/usr/local/bin:/usr/bin:/usr/X11R6/bin:/bin:/usr/games:/opt/gnome/bin:/opt/kde3/bin:/usr/lib/mit/bin:/usr/lib/mit/sbin:/checkpoints/public/R-2-13-1/bin


R --no-restore --no-save --no-readline < sm.test.r > test.out

